[workspace]

members = [
    "crates/*"
]

[package]
name = "agdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db_error = { path = "crates/db_error", version = "<=0.1.0" }

[dev-dependencies]
test_file = { path = "crates/test_file", version = "<=0.1.0" }
