packages:
  - agdb_studio/*

catalog:
  "@kalimahapps/vue-icons": ^1
  "@vueuse/components": ^12
  "@vueuse/core": ^12
  openapi-client-axios: ^7
  vue: ^3
  vue-router: ^4
  "@playwright/test": ^1
  "@rushstack/eslint-patch": ^1
  "@tsconfig/node18": ^1
  "@types/jsdom": ^21
  "@types/node": ^22
  "@vitejs/plugin-vue": ^5
  "@vitest/coverage-v8": ^3
  "@vitest/coverage-istanbul": ^3
  "@vue/eslint-config-prettier": ^10
  "@vue/eslint-config-typescript": ^14
  "@vue/test-utils": ^2
  "@vue/tsconfig": ^0.7
  axios: ^1
  eslint: ^9
  eslint-plugin-vue: ^9
  jsdom: ^26
  less: ^4
  npm-run-all2: ^7
  prettier: ^3
  typescript: ~5
  vite: ^6
  vitest: ^3
  vue-tsc: ^2
