packages:
  - agdb_studio/**
  - agdb_api/**
  - agdb_web/**
  - examples/**

catalog:
  "@eslint/js": ^9
  "@kalimahapps/vue-icons": 1.7.1
  "@playwright/test": ^1
  "@prettier/plugin-php": ^0.22
  "@rushstack/eslint-patch": ^1
  "@testing-library/react": ^16
  "@theguild/remark-mermaid": ^0.2
  "@tsconfig/node18": ^1
  "@types/jsdom": ^21
  "@types/node": ^22
  "@types/react-dom": ^18
  "@types/react": ^18
  "@typescript-eslint/eslint-plugin": ^8
  "@typescript-eslint/parser": ^8
  "@vitejs/plugin-react": ^4
  "@vitejs/plugin-vue": ^5
  "@vitest/coverage-istanbul": ^3
  "@vitest/coverage-v8": ^3
  "@vue/eslint-config-prettier": ^10
  "@vue/eslint-config-typescript": ^14
  "@vue/test-utils": ^2
  "@vue/tsconfig": ^0.7
  "@vueuse/components": ^12
  "@vueuse/core": ^12
  axios: ^1
  copyfiles: ^2
  eslint-config-next: ^15
  eslint-config-prettier: ^10
  eslint-plugin-vue: ^9
  eslint: ^9
  globals: ^16.0.0
  highlight.js: ^11
  jsdom: ^26
  less: ^4
  next: ^15
  nextra-theme-docs: ^3
  nextra: ^3
  npm-run-all2: ^7
  openapi-client-axios: ^7
  openapicmd: ^2
  prettier: ^3
  react-dom: ^18
  react: ^18
  sass: ^1
  turbo: ^2
  typescript-eslint: ^8
  typescript: ~5
  vite: ^6
  vitest: ^3.2.4
  vue-router: ^4
  vue-tsc: ^2
  vue: ^3
