packages:
  - agdb_studio/**
  - agdb_api/**
  - agdb_web_next/**
  - agdb_web/**
  - examples/**

catalog:
  "@eslint/js": ^9
  "@kalimahapps/vue-icons": ^1
  "@openapitools/openapi-generator-cli": ^2
  "@playwright/test": ^1
  "@prettier/plugin-php": ^0.22
  "@rushstack/eslint-patch": ^1
  "@theguild/remark-mermaid": ^0.2
  "@tsconfig/node18": ^18
  "@types/jsdom": ^27
  "@types/node": ^24
  "@typescript-eslint/eslint-plugin": ^8
  "@typescript-eslint/parser": ^8
  "@vitejs/plugin-react": ^4
  "@vitejs/plugin-vue": ^6
  "@vitest/coverage-istanbul": ^4
  "@vitest/coverage-v8": ^4
  "@vue/eslint-config-prettier": ^10
  "@vue/eslint-config-typescript": ^14
  "@vue/test-utils": ^2
  "@vue/tsconfig": ^0.8
  "@vueuse/components": ^14
  "@vueuse/core": ^14
  axios: ^1
  copyfiles: ^2
  eslint-config-prettier: ^10
  eslint-import-resolver-alias: ^1
  eslint-import-resolver-typescript: ^4
  eslint-plugin-import: ^2
  eslint-plugin-vue: ^10
  eslint: ^9
  globals: ^16.0.0
  highlight.js: ^11
  jsdom: ^27
  less: ^4
  npm-run-all2: ^8
  openapi-client-axios: ^7
  openapicmd: ^2
  playwright: ^1
  prettier: ^3
  sass: ^1
  turbo: ^2
  typescript-eslint: ^8
  typescript: ^5
  vite: ^7
  vitest: ^4
  vue-router: ^4
  vue-tsc: ^3
  vue: ^3

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
