packages:
  - agdb_studio/**
  - agdb_api/**
  - agdb_web/**
  - examples/**

catalog:
  '@eslint/js': ^9
  '@kalimahapps/vue-icons': ^1
  '@openapitools/openapi-generator-cli': ^2.24.0
  '@playwright/test': ^1.55.1
  '@prettier/plugin-php': ^0.22
  '@rushstack/eslint-patch': ^1
  '@testing-library/react': ^16
  '@theguild/remark-mermaid': ^0.2
  '@tsconfig/node18': ^18
  '@types/jsdom': ^21
  '@types/node': ^24
  '@types/react': ^18
  '@types/react-dom': ^18
  '@typescript-eslint/eslint-plugin': ^8
  '@typescript-eslint/parser': ^8
  '@vitejs/plugin-react': ^4
  '@vitejs/plugin-vue': ^6
  '@vitest/coverage-istanbul': ^3
  '@vitest/coverage-v8': ^3
  '@vue/eslint-config-prettier': ^10
  '@vue/eslint-config-typescript': ^14
  '@vue/test-utils': ^2
  '@vue/tsconfig': ^0.7
  '@vueuse/components': ^13
  '@vueuse/core': ^13
  axios: ^1
  copyfiles: ^2
  eslint: ^9.36.0
  eslint-config-next: ^15
  eslint-config-prettier: ^10
  eslint-import-resolver-alias: ^1
  eslint-import-resolver-typescript: ^4
  eslint-plugin-import: ^2
  eslint-plugin-vue: ^10
  globals: ^16.0.0
  highlight.js: ^11
  jsdom: ^26
  less: ^4
  next: ^15.5.4
  nextra: ^3
  nextra-theme-docs: ^3
  npm-run-all2: ^8
  openapi-client-axios: ^7
  openapicmd: ^2.7.0
  playwright: ^1
  prettier: ^3.6.2
  react: ^18
  react-dom: ^18
  sass: ^1
  turbo: ^2.5.8
  typescript: ~5.9.2
  typescript-eslint: ^8
  vite: ^7.1.7
  vitest: ^3.2.4
  vue: ^3
  vue-router: ^4
  vue-tsc: ^3
