FROM rust:alpine AS builder
WORKDIR /usr/src/agdb_server
COPY . .
RUN apk add --no-cache musl-dev openssl-dev openssl-libs-static
RUN cargo build --package agdb_server --release

FROM alpine:latest
COPY --from=builder /usr/src/agdb_server/target/release/agdb_server /usr/local/bin/agdb_server
# adduser -D: disable password, -H: do not create home directory
RUN addgroup -g 1000 agdb && \
    adduser -D -H -u 1000 -G agdb agdb && \
    mkdir -p /agdb && \
    chown agdb:agdb /agdb
USER agdb
WORKDIR /agdb
CMD ["/usr/local/bin/agdb_server"]

EXPOSE 3000
