<?php
/**
 * BitwiseOp
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Agnesoft\AgdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * agdb_server
 *
 * Agnesoft Graph Database Server
 *
 * The version of the OpenAPI document: 0.14.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Agnesoft\AgdbApi\Model;
use \Agnesoft\AgdbApi\ObjectSerializer;

/**
 * BitwiseOp Class Doc Comment
 *
 * @category Class
 * @description Bitwise operation for [&#x60;Amend::AddBitwise&#x60;] and [&#x60;Amend::RemoveBitwise&#x60;]. For integers (&#x60;i64&#x60;, &#x60;u64&#x60;) and bytes the bitwise op is applied directly. Other types fall back to &#x60;Add&#x60; or &#x60;Remove&#x60; semantics respectively.
 * @package  Agnesoft\AgdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BitwiseOp
{
    /**
     * Possible values of this enum
     */
    public const _AND = 'And';

    public const _OR = 'Or';

    public const _XOR = 'Xor';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_AND,
            self::_OR,
            self::_XOR
        ];
    }
}


