<?php
/**
 * LogLevelFilter
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Agnesoft\AgdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * agdb_server
 *
 * Agnesoft Graph Database Server
 *
 * The version of the OpenAPI document: 0.12.9
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Agnesoft\AgdbApi\Model;
use \Agnesoft\AgdbApi\ObjectSerializer;

/**
 * LogLevelFilter Class Doc Comment
 *
 * @category Class
 * @package  Agnesoft\AgdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LogLevelFilter
{
    /**
     * Possible values of this enum
     */
    public const OFF = 'off';

    public const ERROR = 'error';

    public const WARN = 'warn';

    public const INFO = 'info';

    public const DEBUG = 'debug';

    public const TRACE = 'trace';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OFF,
            self::ERROR,
            self::WARN,
            self::INFO,
            self::DEBUG,
            self::TRACE
        ];
    }
}


