<?php
/**
 * QueryConditionLogic
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Agdb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * agdb_server
 *
 * Agnesoft Graph Database Server
 *
 * The version of the OpenAPI document: 0.7.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Agdb\Model;
use \Agdb\ObjectSerializer;

/**
 * QueryConditionLogic Class Doc Comment
 *
 * @category Class
 * @description Logical operator for query conditions
 * @package  Agdb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class QueryConditionLogic
{
    /**
     * Possible values of this enum
     */
    public const _AND = 'And';

    public const _OR = 'Or';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_AND,
            self::_OR
        ];
    }
}


