name: agdb

on:
  pull_request:
    branches: ["main"]
    paths:
      - agdb/**
      - agdb_derive/**
      - .github/workflows/agdb.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: diff
        shell: bash
        run: |
          if [[ "$(git diff origin/main --name-only -- agdb/ agdb_derive/ .github/workflows/agdb.yaml)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT) fi

  agdb_analyse:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --package agdb --package agdb_derive --all-targets --all-features -- -D warnings

  agdb_coverage:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: rustup component add llvm-tools-preview
      - run: cargo llvm-cov --package agdb --package agdb_derive --all-features --ignore-filename-regex "agdb_derive" --fail-uncovered-functions 0 --fail-uncovered-lines 0 --show-missing-lines

  agdb_format:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --package agdb --package agdb_derive --check
