name: agdb_api_php

on:
  pull_request:
    branches: ["main"]

jobs:
  diff:
    runs-on: ubuntu-24.04
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: diff
        shell: bash
        run: |
          if [[ "$(git diff origin/main --name-only -- composer.json agdb_api/php/ .github/workflows/agdb_api_php.yaml)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT); fi

  agdb_api_php_analyse:
    runs-on: ubuntu-24.04
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    defaults:
      run:
        working-directory: agdb_api/php
    steps:
      - uses: actions/checkout@v4
      - run: composer install --no-interaction
      - run: ./ci.sh analyse

  agdb_api_php_coverage:
    runs-on: ubuntu-24.04
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    defaults:
      run:
        working-directory: agdb_api/php
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: composer install --no-interaction
      - run: ./ci.sh coverage
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: agdb_api/php/coverage/
          retention-days: 30

  agdb_api_php_format:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    defaults:
      run:
        working-directory: agdb_api/php
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: ./ci.sh format:check
