name: agdb_studio

on:
  pull_request:
    branches: ["main"]
    paths:
      - agdb_studio/**
      - agdb_api/typescript/src/**
      - agdb_api/typescript/package.json
      - agdb_server/openapi/schema.json
      - .github/workflows/agdb_studio.yaml

jobs:
  agdb_studio_analyse:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agdb_studio
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint

  agdb_studio_coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agdb_studio
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test:unit
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: agdb_studio/coverage/
          retention-days: 30

  agdb_studio_e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agdb_studio
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run build
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e
          path: agdb_studio/playwright-report/
          retention-days: 30

  agdb_studio_format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agdb_studio
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run format:check
