name: agdb_studio

on:
  pull_request:
    branches: ["main"]
    paths:
      - agdb_studio/**
      - agdb_api/typescript/**
      - .github/workflows/agdb_studio.yaml

jobs:
  agdb_studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run format:check --filter=agdb_studio
      - run: pnpm run lint:check --filter=agdb_studio
      - run: pnpm run build --filter=agdb_studio
      - run: pnpm run test --filter=agdb_studio
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: agdb_studio/coverage/
          retention-days: 30
      - run: npx playwright install --with-deps
      - run: pnpm run test:e2e --filter=agdb_studio
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e
          path: agdb_studio/playwright-report/
          retention-days: 30
