name: agdb_benchmarks

on:
  pull_request:
    branches: ["main"]
    paths:
      - agdb_benchmarks/**
      - agdb/**
      - agdb_derive/**
      - .github/workflows/agdb_benchmarks.yaml

jobs:
  agdb_benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy
      - run: cargo fmt -p agdb_benchmarks --check
      - run: cargo clippy -p agdb_benchmarks --all-targets --all-features -- -D warnings
      - run: cargo run -p agdb_benchmarks -r
