name: agdb_benchmarks

on:
  pull_request:
    branches: ["main"]

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: diff
        shell: bash
        run: |
          if [[ "$(git diff origin/main --name-only -- agdb_benchmarks/ agdb/src/ agdb/src/Cargo.toml agdb_derive/src/ agdb_derive/Cargo.toml .github/workflows/agdb_benchmarks.yaml)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT); fi

  agdb_benchmarks:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo run --release --package agdb_benchmarks

  agdb_benchmarks_analyse:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo clippy --package agdb_benchmarks --all-targets --all-features -- -D warnings

  agdb_benchmarks_format:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fmt --package agdb_benchmarks --check
