name: agdb_ci

on:
  pull_request:
    branches: ["main"]

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: diff
        shell: bash
        run: |
          if [[ "$(git diff origin/main --name-only -- agdb_ci/ .github/workflows/agdb_ci.yaml Version)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT); fi

  agdb_ci_analyse:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo clippy --package agdb_ci --all-targets --all-features -- -D warnings

  agdb_ci_coverage:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: rustup component add llvm-tools-preview
      - run: cargo llvm-cov --package agdb_ci --all-features --fail-uncovered-functions 0 --fail-uncovered-lines 0 --show-missing-lines

  agdb_ci_format:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fmt --package agdb_ci --check

  validate_version:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          cargo run --release --package agdb_ci
          if [[ "$(git diff --name-only)" != "" ]]; then echo "ERROR: Version changed but some packages have not been updated. Have you forgotten to run agdb_ci?"; exit 1; fi
