name: agdb_web

on:
  pull_request:
    branches: ["main"]
    paths:
      - agdb_web/**
      - .github/workflows/agdb_web.yaml

jobs:
  agdb_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run format:check --filter=agdb_web
      - run: pnpm run lint:check --filter=agdb_web
      - run: pnpm run build --filter=agdb_web
      - run: pnpm run test --filter=agdb_web
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: agdb_web/coverage/
          retention-days: 30
      - run: npx playwright install --with-deps
      - run: pnpm run test:e2e --filter=agdb_web
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e
          path: agdb_web/playwright-report/
          retention-days: 30
