name: agdb_api_php

on:
  pull_request:
    branches: ["main"]
    paths:
      - composer.json
      - agdb_api/php/**
      - .github/workflows/agdb_api_php.yaml

jobs:
  agdb_api_php:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agdb_api/php
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: ./ci.sh format:check
      - run: composer config --global use-parent-dir true
      - run: composer install
      - run: ./ci.sh analyse
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: ./ci.sh coverage
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: agdb_api/php/coverage/
          retention-days: 30
