name: agdb

on:
  pull_request:
    branches: ["main"]
    paths:
      - agdb/**
      - agdb_derive/**
      - .github/workflows/agdb.yaml

jobs:
  agdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fmt -p agdb --check
      - run: cargo clippy -p agdb --all-targets --all-features -- -D warnings
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: rustup component add llvm-tools-preview
      - run: cargo llvm-cov -p agdb --all-features --ignore-filename-regex "agdb_derive" --fail-uncovered-functions 57 --fail-uncovered-lines 271 --show-missing-lines

  # merge with the main job once --doctests is stabilized: https://github.com/taiki-e/cargo-llvm-cov/issues/2
  agdb_doctests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test -p agdb --all-features --doc
