name: agdb_benchmark

on:
  pull_request:
    branches: ["main"]
    paths:
      - agdb_benchmark/**
      - agdb/**
      - agdb_derive/**
      - agdb_server/**
      - agdb_api/src/**
      - agdb_api/Cargo.toml
      - .github/workflows/agdb_benchmark.yaml

jobs:
  agdb_benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy
      - run: cargo fmt -p agdb_benchmark --check
      - run: cargo clippy -p agdb_benchmark --all-targets --all-features -- -D warnings
      - run: ./agdb_server_benchmark.sh
        working-directory: agdb_benchmark
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: server_log
          path: agdb_benchmark/agdb_server_benchmark.log
          retention-days: 30
