name: agdb_web

on:
  pull_request:
    branches: ["main"]

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: diff
        shell: bash
        run: |
          if [[ "$(git diff origin/main --name-only -- agdb_web/ .github/workflows/agdb_web.yaml)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT); fi

  agdb_web_analyse:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    defaults:
      run:
        working-directory: agdb_web
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint

  agdb_web_coverage:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    defaults:
      run:
        working-directory: agdb_web
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: agdb_web/coverage/
          retention-days: 30

  agdb_web_e2e:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    defaults:
      run:
        working-directory: agdb_web
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run build
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e
          path: agdb_web/playwright-report/
          retention-days: 30

  agdb_web_format:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    defaults:
      run:
        working-directory: agdb_web
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run format:check
