name: agdb_ci

on:
  pull_request:
    branches: ["main"]
    paths:
      - agdb_ci/**
      - Version
      - agdb_server/openapi.json
      - agdb_server/test_queries.json
      - .github/workflows/agdb_ci.yaml

jobs:
  agdb_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy
      - run: npm i -g pnpm
      - run: cargo fmt -p agdb_ci --check
      - run: cargo clippy -p agdb_ci --all-targets --all-features -- -D warnings
      - run: cargo run -p agdb_ci -r
      - run: |
          if [[ "$(git diff --name-only)" != "" ]]; then
            git diff
            git diff --name-only
            echo "ERROR: Some packages have not been updated. Plesae run 'cargo run -p agdb_ci -r' and commit the result."
            exit 1
          fi
