name: agdb_web

on:
  pull_request:
    branches: ["main"]
    paths:
      - agdb_web/**
      - .github/workflows/agdb_web.yaml

jobs:
  agdb_web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agdb_web
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: npm run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: agdb_web/coverage/
          retention-days: 30
      - run: npx playwright install --with-deps
      - run: npm run build
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e
          path: agdb_web/playwright-report/
          retention-days: 30
