name: agdb_studio

on:
  pull_request:
    branches: ["main"]
    paths:
      - agdb_studio/**
      - agdb_api/typescript/**
      - .github/workflows/agdb_studio.yaml

jobs:
  agdb_studio:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agdb_studio
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
        working-directory: agdb_api/typescript
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: npm run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: agdb_studio/coverage/
          retention-days: 30
      - run: npx playwright install --with-deps
      - run: npm run build
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e
          path: agdb_studio/playwright-report/
          retention-days: 30
