name: coverage

on:
  push:
    branches: ["main"]
    paths:
      - agdb/**
      - agdb_derive/**
      - agdb_server/**
      - .github/workflows/coverage.yaml

env:
  CARGO_TERM_COLOR: always

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: npm ci && npm run build
        working-directory: agdb_api/typescript
      - run: npm ci && npm run build
        working-directory: agdb_studio
      - run: rustup component add llvm-tools-preview
      - run: cargo llvm-cov -p agdb -p agdb_api -p agdb_server --all-features --ignore-filename-regex "agdb(_derive|_benchmarks)|api.rs" --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
