name: coverage

on:
  push:
    branches: ["main"]
    paths:
      - agdb/**
      - agdb_derive/**
      - agdb_server/**
      - agdb_api/**
      - agdb_studio/**
      - agdb_web/**
      - .github/workflows/coverage.yaml

env:
  CARGO_TERM_COLOR: always

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: rustup component add llvm-tools-preview
      - run: cargo llvm-cov -p agdb -p agdb_api -p agdb_server --all-features --ignore-filename-regex "agdb(_derive|_benchmarks)|api.rs" --lcov --output-path lcov.info
      - run: pnpm i --frozen-lockfile
      - run: pnpm run test
      - run: composer config --global use-parent-dir true
      - run: composer install
      - run: ./ci.sh coverage
        working-directory: agdb_api/php
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
