name: coverage

on:
  push:
    branches: ["main"]
    paths:
      - agdb/**
      - agdb_derive/**

env:
  CARGO_TERM_COLOR: always

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: rustup component add llvm-tools-preview
      - run: cargo llvm-cov --package agdb --ignore-filename-regex agdb_ --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
