name: examples

on:
  pull_request:
    branches: ["main"]

env:
  RUST_PROJECTS: "-p examples_app_db -p examples_indexes -p examples_joins -p examples_schema_migration -p examples_server_client -p examples_strong_types"

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: diff
        shell: bash
        run: |
          if [[ "$(git diff origin/main --name-only -- agdb/ agdb_derive/ agdb_server/ agdb_api/ examples/ .github/workflows/examples.yaml)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT); fi

  agdb_examples_analyse:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo clippy ${{ env.RUST_PROJECTS }} --all-targets --all-features -- -D warnings
      - run: |
          cd examples/server_client_typescript
          npm ci
          npm run lint

  agdb_examples_build:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build ${{ env.RUST_PROJECTS }} --all-features --release
      - run: |
          cd agdb_api/typescript
          npm ci
          npm run build
          cd ../../examples/server_client_typescript
          npm ci
          npm run build

  agdb_examples_format:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fmt ${{ env.RUST_PROJECTS }} --check
      - run: |
          cd examples/server_client_typescript
          npm ci
          npm run format:check
