name: examples

on:
  pull_request:
    branches: ["main"]
    paths:
      - examples/**
      - agdb/**
      - agdb_derive/**
      - agdb_server/**
      - agdb_api/**
      - .github/workflows/examples.yaml

jobs:
  agdb_examples_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fmt -p examples_app_db -p examples_indexes -p examples_joins -p examples_schema_migration -p examples_server_client -p examples_user_types --check
      - run: cargo clippy -p examples_app_db -p examples_indexes -p examples_joins -p examples_schema_migration -p examples_server_client -p examples_user_types --all-targets --all-features -- -D warnings
      - run: cargo build -p examples_app_db -p examples_indexes -p examples_joins -p examples_schema_migration -p examples_server_client -p examples_user_types --all-features -r

  agdb_examples_typescript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/server_client_typescript
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile && pnpm run build
        working-directory: agdb_api/typescript
      - run: pnpm i --frozen-lockfile
      - run: pnpm run format:check
      - run: pnpm run build

  agdb_examples_php:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/server_client_php
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm exec prettier --plugin '@prettier/plugin-php' --check src
      - run: composer config --global use-parent-dir true
      - run: composer install
      - run: vendor/bin/phpstan analyse --level=9 -v src
