name: pr

on:
  pull_request:
    branches: ["main"]
    paths:
      - "**.rs"
      - "Cargo.tml"
      - ".github/workflows/pr.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: rustup component add llvm-tools-preview
      - run: cargo llvm-cov --fail-uncovered-regions 0 --fail-uncovered-functions 0 --fail-uncovered-lines 0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --verbose
