name: pr

on:
  pull_request:
    branches: ["main"]
    paths:
      - "**.rs"
      - "Cargo.tml"
      - ".github/workflows/pr.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --verbose
