name: pr

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: diff
        shell: bash
        run: if [[ "$(git diff origin/main --name-only -- *.rs Cargo.toml .github/workflows/pr.yaml)" != "" ]]; then (echo "::set-output name=diff::true") fi

  analyse:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets -- -D warnings

  build:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose

  coverage:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: rustup component add llvm-tools-preview
      - run: cargo llvm-cov --fail-uncovered-regions 126 --fail-uncovered-functions 0 --fail-uncovered-lines 1

  test:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.diff == 'true'
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --verbose
