name: pr_title

on:
  pull_request:
    branches: ["main"]
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  title_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const regex = RegExp("^\\[(api|ci|db|docs|server|studio|tests|web)\\] .+ #[\\d]+$")
            const title = context.payload.pull_request.title

            if (!regex.test(title)) {
                core.setFailed(`PR title "${title}" failed to pass regex - ${regex}. Correct example: [ci] description #1`);
            }
