name: release-test

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  new_version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.new_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cargo search ^agdb --limit 1 -q
          cargo search agdb --limit 1 -q
          cargo search flagdb --limit 1 -q
          PUBLISHED_VERSION=$(cargo search ^agdb --limit 1 -q | head -n 1 | cut -d '"' -f 2)
          CURRENT_VERSION=$(cat Cargo.toml | grep version | head -n 1 | cut -d '"' -f 2)
          if [[ "${PUBLISHED_VERSION}" != "${CURRENT_VERSION}" ]]; then echo "new_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT"; fi
